### ISSUE TITLE
Execution error 

### ISSUE THREAD

**Issue by aconejos** [tonyflo/facebook-download-photos#3]
>>>aconejos ~/projects/personal/facebook-download-photos (main)
$python download.py -e XXXXXXXXXXX -p XXXXXXXXXXXXXXX! -a by
Traceback (most recent call last):
  File "download.py", line 15, in <module>
    from webdriver_manager.chrome import ChromeDriverManager
  File "/home/aconejos/env/fb/lib/python3.8/site-packages/webdriver_manager/chrome.py", line 7, in <module>
    from webdriver_manager.drivers.chrome import ChromeDriver
  File "/home/aconejos/env/fb/lib/python3.8/site-packages/webdriver_manager/drivers/chrome.py", line 1, in <module>
    from packaging import version
ModuleNotFoundError: No module named 'packaging'
(fb)

have not been able to find where this "packaging" import should come from..
(i am using WSL ubuntu)

**Comment by tonyflo** [comment]
Does this work? https://stackoverflow.com/questions/42222096/no-module-named-packaging
